// IMPORTS
import { FORGOTPASSWORD, LOGINUSER, LOGOUTUSER, REGISTERUSER, RESETPASSWORD } from "./Authentication.Service";
import { GETCART, UPDATECART } from "./Cart.Service"
import { CREATECONTACT, DELETECONTACT, GETALLCONTACT, GETCONTACTDETAILS, UPDATECONTACTSTATUS, COUNTCONTACT } from "./Contact.Service"
import { DELETEORDER, GETALLORDERS, GETMYORDERS, GETORDERDETAILS, UPDATEORDERSTATUS, COUNTORDER } from "./Order.Service"
import { GETRAZORPAYKEYID, RAZORPAYCREATEORDER, VERIFYPAYMENT } from "./Payment.Service"
import { ADDORUPDATEPRODUCTREVIEW, CREATEPRODUCT, DELETEPRODUCT, DELETEPRODUCTREVIEW, DELETEUSERREVIEW, GETPRODUCTDETAILS, GETPRODUCTS, UPDATEPRODUCT, COUNTPRODUCT } from "./Products.Service"
import { DELETEUSER, GETALLUSERS, GETME, GETUSERDETAIL, UPDATEMYPROFILE, UPDATEUSERROLE, COUNTUSER } from "./User.Service"

// EXPORTS
export {
    FORGOTPASSWORD, LOGINUSER, LOGOUTUSER, REGISTERUSER, RESETPASSWORD, GETCART, UPDATECART, CREATECONTACT, DELETECONTACT, GETALLCONTACT, GETCONTACTDETAILS, UPDATECONTACTSTATUS, COUNTCONTACT, DELETEORDER, GETALLORDERS, GETMYORDERS, GETORDERDETAILS, UPDATEORDERSTATUS, COUNTORDER, ADDORUPDATEPRODUCTREVIEW, CREATEPRODUCT, DELETEPRODUCT, DELETEPRODUCTREVIEW, DELETEUSERREVIEW, GETPRODUCTDETAILS, GETPRODUCTS, UPDATEPRODUCT, COUNTPRODUCT, DELETEUSER, GETALLUSERS, GETME, GETUSERDETAIL, UPDATEMYPROFILE, UPDATEUSERROLE, COUNTUSER, GETRAZORPAYKEYID, RAZORPAYCREATEORDER, VERIFYPAYMENT
}