// IMPORTS
import { FORGOTPASSWORD, LOGINUSER, LOGOUTUSER, REGISTERUSER, RESETPASSWORD } from "./Authentication.Service";
import { GETCART, UPDATECART } from "./Cart.Service"
import { CREATECONTACT, DELETECONTACT, GETALLCONTACT, GETCONTACTDETAILS, UPDATECONTACTSTATUS } from "./Contact.Service"
import { DELETEORDER, GETALLORDERS, GETMYORDERS, GETORDERDETAILS, UPDATEORDERSTATUS } from "./Order.Service"
import { GETRAZORPAYKEYID, RAZORPAYCREATEORDER, VERIFYPAYMENT } from "./Payment.Service"
import { ADDORUPDATEPRODUCTREVIEW, CREATEPRODUCT, DELETEPRODUCT, DELETEPRODUCTREVIEW, DELETEUSERREVIEW, GETPRODUCTDETAILS, GETPRODUCTS, UPDATEPRODUCT } from "./Products.Service"
import { DELETEUSER, GETALLUSERS, GETME, GETUSERDETAIL, UPDATEMYPROFILE, UPDATEUSERROLE } from "./User.Service"

// EXPORTS
export {
    FORGOTPASSWORD, LOGINUSER, LOGOUTUSER, REGISTERUSER, RESETPASSWORD, GETCART, UPDATECART, CREATECONTACT, DELETECONTACT, GETALLCONTACT, GETCONTACTDETAILS, UPDATECONTACTSTATUS, DELETEORDER, GETALLORDERS, GETMYORDERS, GETORDERDETAILS, UPDATEORDERSTATUS, ADDORUPDATEPRODUCTREVIEW, CREATEPRODUCT, DELETEPRODUCT, DELETEPRODUCTREVIEW, DELETEUSERREVIEW, GETPRODUCTDETAILS, GETPRODUCTS, UPDATEPRODUCT, DELETEUSER, GETALLUSERS, GETME, GETUSERDETAIL, UPDATEMYPROFILE, UPDATEUSERROLE, GETRAZORPAYKEYID, RAZORPAYCREATEORDER, VERIFYPAYMENT
}